import pandas as pd
from random import choice, randint, choices
from datetime import datetime, timedelta


CRYPTO = [
    "bitcoin", "bitcoin-cash", "dai", "dash", "dogecoin", "litecoin", "monero",
    "nano", "ripple", "stellar", "tether", "zcash", "algorand", "cardano", "cosmos",
    "eos", "ethereum", "ethereum-classic", "icon", "kusama", "lisk", "polkadot", "tron",
    "augur", "balancer", "gnosis", "kava", "melon", "chainlink", "filecoin", "storj",
    "basic-attention-token"
]

CLASIFF = {
    "payment" : [
        "bitcoin", "bitcoin-cash", "dai", "dash",
        "dogecoin", "litecoin", "monero", "nano",
        "ripple", "stellar", "tether", "zcash",
    ],
    "infrastructure" : [
        "algorand", "cardano", "cosmos", "eos",
        "ethereum", "ethereum-classic", "icon",
        "kusama", "lisk", "polkadot", "tron",
    ],
    "financial" : [
        "augur", "balancer", "gnosis", "kava",
        "melon", 
    ],
    "service" : [
        "chainlink", "filecoin", "storj",
    ],
    "media&entretainment" : [
        "basic-attention-token",
    ]
}

COUNTRY = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua & Deps',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Rep',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo {Democratic Rep}',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea North',
    'Korea South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'St Kitts & Nevis',
    'St Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome & Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad & Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
]

PEOPLE = pd.read_csv("data/pantheon.tsv", sep='\t')["name"].to_list()

EXT_FACT_CAT = {
    "social" : {    
        "politico" : [
            "Entrevista con figura politica",
            "Medidas politicas a favor de cryptos",
            "Medidas politicas en contra de cryptos",
        ],
        "mediatico" : [
            "Tweet de celebridad",
            "Post en Instagram",
            "Entrevista con celebridad",
            "Critica de celebridad",
        ],
        "economica" : [
            "Pais acepta crypto moneda como divisa",
            "Pais rechaza crypto moneda como divisa",
            "Permiten cobros con cryptos",
            "Prohiben cobros con cryptos",
            "Inversion en el proyecto",
        ]
    },
    "cientifico" : {
        "natural" : [
            "Terremoto",
            "Crisis energetica",
            "Emergencia hidrica",
            "Apagon",
            "Tsunami",
        ],

        "tecnologia" : [
            "Avance tecnologico en la mineria",
            "Mejora en la tecnologia de semiconductores",
            "Suba en el precio de tarjetas de video",
            "Bajada en el precio de tarjetas de video"
        ],
    }
}

INIT_DATE = datetime(2021, 8,26)
LAST_DATE = datetime(2021, 9, 26)


# https://es.stackoverflow.com/questions/110479/rango-de-fechas-c%C3%B3mo-crear-una-lista-que-contenga-como-items-todos-los-dias-en?newreg=2d7212269c3d4bff9cc9ec1a59676c51
DATES = [(INIT_DATE + timedelta(days=d)).strftime("%d-%m-%Y") for d in range((LAST_DATE - INIT_DATE).days)]
